In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
!pip install pandas
import pandas as pd

In [4]:
df=pd.read_csv('дом_электропотребление_за_месяц.csv')
df

Квартира  Этаж  Подъезд       кВт_ч
0           1     1        1  219.093876
1           2     1        1  280.788630
2           3     1        1  159.856605
3           4     1        1  302.470699
4           5     1        1  168.830702
..        ...   ...      ...         ...
120         1     5        5  247.062431
121         2     5        5  179.620206
122         3     5        5  113.492054
123         4     5        5  300.869933
124         5     5        5  200.702516

[125 rows x 4 columns]

In [9]:
array=np.array(df)
array

array([[  1.        ,   1.        ,   1.        , 219.0938762 ],
       [  2.        ,   1.        ,   1.        , 280.78863   ],
       [  3.        ,   1.        ,   1.        , 159.8566046 ],
       [  4.        ,   1.        ,   1.        , 302.470699  ],
       [  5.        ,   1.        ,   1.        , 168.8307018 ],
       [  1.        ,   2.        ,   1.        , 165.7689769 ],
       [  2.        ,   2.        ,   1.        , 233.4383484 ],
       [  3.        ,   2.        ,   1.        , 215.7460783 ],
       [  4.        ,   2.        ,   1.        , 190.3926673 ],
       [  5.        ,   2.        ,   1.        , 319.4884754 ],
       [  1.        ,   3.        ,   1.        , 197.7287686 ],
       [  2.        ,   3.        ,   1.        , 199.9909148 ],
       [  3.        ,   3.        ,   1.        , 254.4097895 ],
       [  4.        ,   3.        ,   1.        , 222.1239341 ],
       [  5.        ,   3.        ,   1.        , 163.0712926 ],
       [  1.        ,   4

In [10]:
df2=array[:, 3]
df2 #массив данных по энергопотреблению по дому

array([219.0938762 , 280.78863   , 159.8566046 , 302.470699  ,
       168.8307018 , 165.7689769 , 233.4383484 , 215.7460783 ,
       190.3926673 , 319.4884754 , 197.7287686 , 199.9909148 ,
       254.4097895 , 222.1239341 , 163.0712926 , 217.7872049 ,
       161.8553952 , 124.8392325 , 216.4079546 , 193.4453656 ,
       229.3518208 , 151.6873165 , 201.4187646 , 189.7737667 ,
       140.8575179 , 226.236886  , 229.7148234 , 226.250022  ,
       243.6868388 , 207.5860321 , 168.0141847 , 170.0840522 ,
       195.1402881 , 282.0521899 , 184.3345104 , 151.9820245 ,
       105.2272933 ,  99.48398647, 259.1629768 , 151.7971854 ,
       128.4492642 , 192.1042703 , 166.1638634 , 326.0954937 ,
       166.5663739 , 192.2321592 , 239.1497264 ,  86.61988828,
       120.1110015 , 217.0031612 , 199.550679  , 219.2183203 ,
       270.9528287 , 155.9326461 , 221.7926628 , 251.6870983 ,
       157.3538498 , 263.9928968 , 177.3185029 , 197.0617388 ,
       197.2951816 , 205.7292355 , 173.6373828 , 208.33

In [15]:
df3=df2[:27]
df3

array([219.0938762, 280.78863  , 159.8566046, 302.470699 , 168.8307018,
       165.7689769, 233.4383484, 215.7460783, 190.3926673, 319.4884754,
       197.7287686, 199.9909148, 254.4097895, 222.1239341, 163.0712926,
       217.7872049, 161.8553952, 124.8392325, 216.4079546, 193.4453656,
       229.3518208, 151.6873165, 201.4187646, 189.7737667, 140.8575179,
       226.236886 , 229.7148234])

In [16]:
cube_3D=df3.reshape(3, 3, 3)
cube_3D

array([[[219.0938762, 280.78863  , 159.8566046],
        [302.470699 , 168.8307018, 165.7689769],
        [233.4383484, 215.7460783, 190.3926673]],

       [[319.4884754, 197.7287686, 199.9909148],
        [254.4097895, 222.1239341, 163.0712926],
        [217.7872049, 161.8553952, 124.8392325]],

       [[216.4079546, 193.4453656, 229.3518208],
        [151.6873165, 201.4187646, 189.7737667],
        [140.8575179, 226.236886 , 229.7148234]]])

In [18]:
df2.max()

326.0954937

In [19]:
df2.min()

71.91286877

In [20]:
df2.mean()

194.45217738888

In [22]:
np.median(df2)

197.0617388

In [46]:
a=np.quantile(df2, [0.25])
a

array([158.6359254])

In [47]:
b=np.quantile(df2, [0.75])
b

array([226.250022])

In [48]:
c=np.quantile(df2, [0.5])
c

array([197.0617388])

In [49]:
q=(b-a)/2 #квантильное расстояние
q

array([33.8070483])

In [50]:
np.var(df2)

2769.049246722753

In [51]:
np.std(df2)

52.6217564009674

In [54]:
range1=df2.mean()+np.std(df2)
range1

247.0739337898474

In [55]:
range2=df2.mean()-np.std(df2)
range2

141.8304209879126

In [29]:
cube_3Da = cube_3D[0]
cube_3Db = cube_3D[1]
cube_3Dc = cube_3D[2]

In [33]:
point1=cube_3Da.reshape(1,9)
point2=cube_3Db.reshape(1,9)
point3=cube_3Dc.reshape(1,9)

In [42]:
square1_2 = np.square(point1 - point2) # расчет эвклидова расстояния для 1 и 2 подъездов 3D куба
sum_square1_2 = np.sum(square1_2)
sum_square1_2

31192.492942997174

In [43]:
square1_3 = np.square(point1 - point3) # расчет эвклидова расстояния для 1 и 3 подъездов 3D куба
sum_square1_3 = np.sum(square1_3)
sum_square1_3

47066.98447673551

In [44]:
square3_2 = np.square(point3 - point2) # расчет эвклидова расстояния для 3 и 2 подъездов 3D куба
sum_square3_2 = np.sum(square3_2)
sum_square3_2

44261.679403293725

In [67]:
!pip install seaborn
import seaborn as sns

     -------------------------------------- 292.8/292.8 KB 1.5 MB/s eta 0:00:00


In [68]:
sns_plot = sns.distplot(df2)
fig = sns_plot.get_figure()

C:\!Disk_D!\VE\VE\lib\site-packages\seaborn\distributions.py:2619: FutureWarning: `distplot` is a deprecated function and will be removed in a future version. Please adapt your code to use either `displot` (a figure-level function with similar flexibility) or `histplot` (an axes-level function for histograms).
  warnings.warn(msg, FutureWarning)


In [ ]:
# близко с нормальному распределению, немного растянуто вправо

In [90]:
print("Этаж1\n""max =", df2[:25].max(), "\n" "min =", df2[:25].min(), "\n" "среднее =", df2[:25].mean(), "\n" "стандартное отклонение =", df2[:25].std(), "\n" "квантили =", np.quantile(df2, [0.25]), " и ", np.quantile(df2, [0.75]))


Этаж1
max = 319.4884754 
min = 124.8392325 
среднее = 204.824963872 
стандартное отклонение = 47.1812777137637 
квантили = [158.6359254]  и  [226.250022]


In [101]:
d = {'stats' : ['min', 'max', 'среднее', 'стандартное отклонение', 'квантиль 25%', 'квантиль 75%'],
    'Подъезд 1' : [df2[:25].max(), df2[:25].min(), df2[:25].mean(), df2[:25].std(), np.quantile(df2[:25], 0.25), np.quantile(df2[:25], 0.75)],
    'Подъезд 2' : [df2[26:50].max(), df2[26:50].min(), df2[26:50].mean(), df2[26:50].std(), np.quantile(df2[26:50], 0.25), np.quantile(df2[26:50], 0.75)],
    'Подъезд 3' : [df2[51:75].max(), df2[51:75].min(), df2[51:75].mean(), df2[51:75].std(), np.quantile(df2[51:75], 0.25), np.quantile(df2[51:75], 0.75)],
    'Подъезд 4' : [df2[76:100].max(), df2[76:100].min(), df2[76:100].mean(), df2[76:100].std(), np.quantile(df2[76:100], 0.25), np.quantile(df2[76:100], 0.75)],
    'Подъезд 5' : [df2[101:125].max(), df2[101:125].min(), df2[101:125].mean(), df2[101:125].std(), np.quantile(df2[101:125], 0.25), np.quantile(df2[101:125], 0.75)]}

In [102]:
df = pd.DataFrame(data=d)

In [103]:
df

stats   Подъезд 1   Подъезд 2   Подъезд 3   Подъезд 4  \
0                     min  319.488475  326.095494  270.952829  303.548001   
1                     max  124.839232   86.619888  114.932342  134.108006   
2                 среднее  204.824964  187.875484  206.494590  201.364731   
3  стандартное отклонение   47.181278   57.954208   42.288435   50.644816   
4            квантиль 25%  165.768977  151.935815  172.955144  157.581733   
5            квантиль 75%  222.123934  227.116222  243.769756  240.960708   

    Подъезд 5  
0  300.869933  
1   81.898616  
2  176.886590  
3   54.453230  
4  123.949315  
5  221.511010

In [108]:
flats_df = df2.reshape(25, 5)
flats_df

array([[219.0938762 , 280.78863   , 159.8566046 , 302.470699  ,
        168.8307018 ],
       [165.7689769 , 233.4383484 , 215.7460783 , 190.3926673 ,
        319.4884754 ],
       [197.7287686 , 199.9909148 , 254.4097895 , 222.1239341 ,
        163.0712926 ],
       [217.7872049 , 161.8553952 , 124.8392325 , 216.4079546 ,
        193.4453656 ],
       [229.3518208 , 151.6873165 , 201.4187646 , 189.7737667 ,
        140.8575179 ],
       [226.236886  , 229.7148234 , 226.250022  , 243.6868388 ,
        207.5860321 ],
       [168.0141847 , 170.0840522 , 195.1402881 , 282.0521899 ,
        184.3345104 ],
       [151.9820245 , 105.2272933 ,  99.48398647, 259.1629768 ,
        151.7971854 ],
       [128.4492642 , 192.1042703 , 166.1638634 , 326.0954937 ,
        166.5663739 ],
       [192.2321592 , 239.1497264 ,  86.61988828, 120.1110015 ,
        217.0031612 ],
       [199.550679  , 219.2183203 , 270.9528287 , 155.9326461 ,
        221.7926628 ],
       [251.6870983 , 157.3538498 , 263.992

In [109]:
flats = {'stats' : ['min', 'max', 'среднее', 'стандартное отклонение', 'квантиль 25%', 'квантиль 75%'],
    'Квартира 1' : [flats_df[:, 0].max(), flats_df[:, 0].min(), flats_df[:, 0].mean(), flats_df[:, 0].std(), np.quantile(flats_df[:, 0], 0.25), np.quantile(flats_df[:, 0], 0.75)],
    'Квартира 2' : [flats_df[:, 1].max(), flats_df[:, 1].min(), flats_df[:, 1].mean(), flats_df[:, 1].std(), np.quantile(flats_df[:, 1], 0.25), np.quantile(flats_df[:, 1], 0.75)],
    'Квартира 3' : [flats_df[:, 2].max(), flats_df[:, 2].min(), flats_df[:, 2].mean(), flats_df[:, 2].std(), np.quantile(flats_df[:, 2], 0.25), np.quantile(flats_df[:, 2], 0.75)],
    'Квартира 4' : [flats_df[:, 3].max(), flats_df[:, 3].min(), flats_df[:, 3].mean(), flats_df[:, 3].std(), np.quantile(flats_df[:, 3], 0.25), np.quantile(flats_df[:, 3], 0.75)],
    'Квартира 5' : [flats_df[:, 4].max(), flats_df[:, 4].min(), flats_df[:, 4].mean(), flats_df[:, 4].std(), np.quantile(flats_df[:, 4], 0.25), np.quantile(flats_df[:, 4], 0.75)]}

In [110]:
df_flats = pd.DataFrame(data=flats)
df_flats

stats  Квартира 1  Квартира 2  Квартира 3  Квартира 4  \
0                     min  275.801969  280.788630  301.960321  326.095494   
1                     max   71.912869  105.227293   86.619888  120.111002   
2                 среднее  187.600732  196.994565  184.313761  211.754257   
3  стандартное отклонение   52.653137   37.556276   59.886287   55.089526   
4            квантиль 25%  151.982024  170.084052  124.839232  161.736419   
5            квантиль 75%  229.351821  219.218320  223.703340  243.686839   

   Квартира 5  
0  319.488475  
1  111.482715  
2  191.597572  
3   50.769007  
4  159.595871  
5  215.886371

In [111]:
floors_df = df2.reshape(5, 5, 5)
floors_df

array([[[219.0938762 , 280.78863   , 159.8566046 , 302.470699  ,
         168.8307018 ],
        [165.7689769 , 233.4383484 , 215.7460783 , 190.3926673 ,
         319.4884754 ],
        [197.7287686 , 199.9909148 , 254.4097895 , 222.1239341 ,
         163.0712926 ],
        [217.7872049 , 161.8553952 , 124.8392325 , 216.4079546 ,
         193.4453656 ],
        [229.3518208 , 151.6873165 , 201.4187646 , 189.7737667 ,
         140.8575179 ]],

       [[226.236886  , 229.7148234 , 226.250022  , 243.6868388 ,
         207.5860321 ],
        [168.0141847 , 170.0840522 , 195.1402881 , 282.0521899 ,
         184.3345104 ],
        [151.9820245 , 105.2272933 ,  99.48398647, 259.1629768 ,
         151.7971854 ],
        [128.4492642 , 192.1042703 , 166.1638634 , 326.0954937 ,
         166.5663739 ],
        [192.2321592 , 239.1497264 ,  86.61988828, 120.1110015 ,
         217.0031612 ]],

       [[199.550679  , 219.2183203 , 270.9528287 , 155.9326461 ,
         221.7926628 ],
        [251.6870

In [116]:
floors_df[:, 0, :]

array([[219.0938762 , 280.78863   , 159.8566046 , 302.470699  ,
        168.8307018 ],
       [226.236886  , 229.7148234 , 226.250022  , 243.6868388 ,
        207.5860321 ],
       [199.550679  , 219.2183203 , 270.9528287 , 155.9326461 ,
        221.7926628 ],
       [145.2841794 , 201.2613737 , 301.9603211 , 252.0348023 ,
        303.5480015 ],
       [ 71.91286877, 229.6512478 , 100.814039  , 220.7802337 ,
        159.5958706 ]])

In [117]:
floors = {'stats' : ['min', 'max', 'среднее', 'стандартное отклонение', 'квантиль 25%', 'квантиль 75%'],
    'Этаж 1' : [floors_df[:, 0, :].max(), floors_df[:, 0, :].min(), floors_df[:, 0, :].mean(), floors_df[:, 0, :].std(), np.quantile(floors_df[:, 0, :], 0.25), np.quantile(floors_df[:, 0, :], 0.75)],
    'Этаж 2' : [floors_df[:, 1, :].max(), floors_df[:, 1, :].min(), floors_df[:, 1, :].mean(), floors_df[:, 1, :].std(), np.quantile(floors_df[:, 1, :], 0.25), np.quantile(floors_df[:, 1, :], 0.75)],
    'Этаж 3' : [floors_df[:, 2, :].max(), floors_df[:, 2, :].min(), floors_df[:, 2, :].mean(), floors_df[:, 2, :].std(), np.quantile(floors_df[:, 2, :], 0.25), np.quantile(floors_df[:, 2, :], 0.75)],
    'Этаж 4' : [floors_df[:, 3, :].max(), floors_df[:, 3, :].min(), floors_df[:, 3, :].mean(), floors_df[:, 3, :].std(), np.quantile(floors_df[:, 3, :], 0.25), np.quantile(floors_df[:, 3, :], 0.75)],
    'Этаж 5' : [floors_df[:, 4, :].max(), floors_df[:, 4, :].min(), floors_df[:, 4, :].mean(), floors_df[:, 4, :].std(), np.quantile(floors_df[:, 4, :], 0.25), np.quantile(floors_df[:, 4, :], 0.75)]}

In [118]:
df_floors = pd.DataFrame(data=floors)
df_floors

stats      Этаж 1      Этаж 2      Этаж 3      Этаж 4  \
0                     min  303.548001  319.488475  259.162977  326.095494   
1                     max   71.912869   81.898616   99.483986  111.482715   
2                 среднее  212.752208  198.403195  177.793563  185.165057   
3  стандартное отклонение   57.953489   56.216358   42.982436   46.043229   
4            квантиль 25%  168.830702  165.768977  148.177453  161.855395   
5            квантиль 75%  243.686839  233.438348  205.729235  202.405593   

       Этаж 5  
0  300.869933  
1   86.619888  
2  198.146865  
3   51.293072  
4  161.736419  
5  239.149726