In [2]:
!pip install numpy

You should consider upgrading via the 'd:\anna\ve\scripts\python.exe -m pip install --upgrade pip' command.


In [4]:
import numpy as np

In [5]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
B = A.copy()
B

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
A = np.zeros((2, 3))
A

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
B = np.ones((3, 2))
B

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.zeros_like(A)
B

array([[0, 0, 0],
       [0, 0, 0]])

In [12]:
A = np.eye(3)
A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
From = 2.5
To = 7
Step = 0.5
A = np.arange(From, To, Step)
A

array([2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [14]:
A = np.arange(5)
A

array([0, 1, 2, 3, 4])

In [15]:
A = np.arange(10, 15)
A

array([10, 11, 12, 13, 14])

In [19]:
A = np.ones((3, 2), 'str')
A

array([['1', '1'],
       ['1', '1'],
       ['1', '1']], dtype='<U1')

In [24]:
A = np.ones((3, 2))
B = A.astype('uint')
B

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=uint32)

In [25]:
A = np.arange(5)
print(A)
A[0:4:2]

[0 1 2 3 4]


array([0, 2])

In [30]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = A[:, ::-1]
print("A", A)
print("B", B)
print(A)
B[0, 0] = 0
print(A)

A [[1 2 3]
 [4 5 6]]
B [[3 2 1]
 [6 5 4]]
[[1 2 3]
 [4 5 6]]
[[1 2 0]
 [4 5 6]]


In [38]:
A = np.array([["10000", "20000", "30000"], ["40000", "50000", "60000"]])
I = np.array([[False, False, True], [ True, False, True]])
A[I] = "pizza"
print(A)

[['10000' '20000' 'pizza']
 ['pizza' '50000' 'pizza']]


In [41]:
A = np.array([[1, 2, 3], [4, 5, 6]])

I1 = np.array([[False, False, True], [True, False, True]])
I2 = np.array([[False, True, False], [False, False, True]])

B = A.copy()
C = A.copy()
D = A.copy()

B[np.logical_and(I1, I2)] = 0
C[np.logical_or(I1, I2)] = 0
D[np.logical_not(I1)] = 0

print(B)
print(C)
print(D)



[[1 2 3]
 [4 5 0]]
[[1 0 0]
 [0 5 0]]
[[0 0 3]
 [4 0 6]]
